version: '3.4'

services:
  db:
    container_name: ett-backend-postgres-compose
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ett-backend:
    container_name: ett-backend-api-compose
    image: ett-backend-api-compose
    build:
      context: .
      dockerfile: ./local.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - CONNECTION=Host=host.docker.internal;Username=postgres;Password=mysecretpassword;Database=postgres
      - API_USERNAME=callibrity
      - API_PASSWORD=callibrity2017
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db

volumes:
  pgdata: