name: Build and Test

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - run: dotnet restore

      - run: dotnet build --configuration Release --no-restore

      - run: dotnet test --no-restore --verbosity normal
