name: On Create Release

on:
  release:
    types: 
      - published

env:
  RUN_REGION: us-east4
  MEMORY: 2048Mi
  CPU: 2000m
  CONTAINER_REGISTRY: intranet-api
  SERVICE_NAME: intranet-api-production
  PORT: 80

jobs:
  deploy:
    name: Deploy to Cloud Run Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      # Check for image, add release tag to image tags
      - run: |-
          gcloud container images add-tag \
            --quiet \
            "gcr.io/${{ secrets.RUN_PROJECT }}/$CONTAINER_REGISTRY:$GITHUB_SHA" \
            "gcr.io/${{ secrets.RUN_PROJECT }}/$CONTAINER_REGISTRY:${GITHUB_REF#refs/*/}"
  
      # Deploy image to Cloud Run
      - run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --memory "$MEMORY" \
            --cpu "$CPU" \
            --image "gcr.io/${{ secrets.RUN_PROJECT }}/$CONTAINER_REGISTRY:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated \
            --port $PORT \
            --update-env-vars "ASPNETCORE_ENVIRONMENT=Production"